baseurl = "madeof.info/"
languageCode = "en-us"
title = "We are made of information"
# Define how many pages appear per site
paginate = 3
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "lipoo"
theme = "hugo-minimalist-theme"
relativeURLs = true

[params]
    site_author = "Karl Horschel"
    site_description = "madeof.info Blog"
    location = "Earth"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title ="We are made of information"
    copyright = "Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "lipoo"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
